<a href="https://colab.research.google.com/github/nrios256-create/analisis_datos/blob/main/merging_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [9]:
movie = pd.read_csv('https://raw.githubusercontent.com/Gustavo-Bruges/movies/main/movies.csv')
ratings = pd.read_csv('https://raw.githubusercontent.com/Gustavo-Bruges/movies/main/ratings.csv')
#esto lo traemos de github del profe

In [11]:
print(movie.shape)
print(ratings.shape)

(4803, 5)
(4803, 4)

In [13]:
print('movie dataset')
print(movie.head())
print('')
print(50*'*')
print('rating dataset')
print(ratings.head())

movie dataset
   Unnamed: 0     id                 title  popularity release_date
0           0    257          Oliver Twist   20.415572   2005-09-23
1           1  14290  Better Luck Tomorrow    3.877036   2002-01-12
2           2  38365             Grown Ups   38.864027   2010-06-24
3           3   9672              Infamous    3.680896   2006-11-16
4           4  12819       Alpha and Omega   12.300789   2010-09-17

**************************************************
rating dataset
   Unnamed: 0      id  vote_average  vote_count
0           0   19995           7.2     11800.0
1           1     285           6.9      4500.0
2           2  206647           6.3      4466.0
3           3   49026           7.6      9106.0
4           4   49529           6.1      2124.0

In [15]:
movie_ratings = movie.merge(ratings, on='id')
movie_ratings.head()
movie_ratings.drop(['Unnamed: 0_x','Unnamed: 0_y'],axis=1,inplace=True)
#unir la dataframe

In [18]:
movie_ratings = movie.merge(ratings, on='id',suffixes=('_movie','_rating'))
movie_ratings.head()

,Unnamed: 0_movie,id,title,popularity,release_date,Unnamed: 0_rating,vote_average,vote_count
0,0,257,Oliver Twist,20.415572,2005-09-23,667,6.7,274.0
1,1,14290,Better Luck Tomorrow,3.877036,2002-01-12,4634,6.5,27.0
2,2,38365,Grown Ups,38.864027,2010-06-24,520,6.0,1705.0
3,3,9672,Infamous,3.680896,2006-11-16,2778,6.4,60.0
4,4,12819,Alpha and Omega,12.300789,2010-09-17,2162,5.3,124.0

In [19]:
movie_genres = pd.read_csv('https://raw.githubusercontent.com/Gustavo-Bruges/movies/refs/heads/main/movie_to_genres.csv')

In [20]:
movie_genres.head()

   Unnamed: 0  movie_id            genre
0           0         5            Crime
1           1         5           Comedy
2           2        11  Science Fiction
3           3        11           Action
4           4        11        Adventure

In [24]:
movie_genres = movie_genres.drop(columns=['Unnamed: 0'], axis=1, errors='ignore') #axis=1 : avisarle que me avise la columna, #errors='ignore' : si la columna existe la elimina, de lo contrario sigue con el codigo normal
movie_genres.head()

   movie_id            genre
0         5            Crime
1         5           Comedy
2        11  Science Fiction
3        11           Action
4        11        Adventure

In [26]:
print(movie.head())
print(movie_genres.head())

   Unnamed: 0     id                 title  popularity release_date
0           0    257          Oliver Twist   20.415572   2005-09-23
1           1  14290  Better Luck Tomorrow    3.877036   2002-01-12
2           2  38365             Grown Ups   38.864027   2010-06-24
3           3   9672              Infamous    3.680896   2006-11-16
4           4  12819       Alpha and Omega   12.300789   2010-09-17
   movie_id            genre
0         5            Crime
1         5           Comedy
2        11  Science Fiction
3        11           Action
4        11        Adventure

In [25]:
movie_generos = movie.merge(movie_genres,left_on='id',right_on='movie_id')
movie_generos.head()

,Unnamed: 0,id,title,popularity,release_date,movie_id,genre
0,0,257,Oliver Twist,20.415572,2005-09-23,257,Crime
1,0,257,Oliver Twist,20.415572,2005-09-23,257,Drama
2,0,257,Oliver Twist,20.415572,2005-09-23,257,Family
3,1,14290,Better Luck Tomorrow,3.877036,2002-01-12,14290,Crime
4,1,14290,Better Luck Tomorrow,3.877036,2002-01-12,14290,Drama

In [31]:
crimen = movie_generos[movie_generos['genre']=='Crime']

In [36]:
menos_popular = crimen.loc[crimen['popularity'].idxmin()]
menos_popular.head()
#aqui uso loc para buscar las fila

Unnamed: 0                          3827
id                                378237
title           Amidst the Devil's Wings
popularity                      0.018087
release_date                  2014-12-01
Name: 9666, dtype: object

In [43]:
sci_movie = movie_generos[movie_generos['genre']== 'Science Fiction']
print(sci_movie.shape)
action_movie = movie_generos[movie_generos['genre']== 'Action']
print(action_movie.shape)

(535, 7)
(1154, 7)

In [44]:
print(sci_movie.head())
print(sci_movie.shape)
print(action_movie.head())
print(action_movie.shape)

    Unnamed: 0     id                         title  popularity release_date  \
9            5  49529                   John Carter   43.926995   2012-03-07
17           9  18841  The Lost Skeleton of Cadavra    1.680525   2001-09-12
21          10  76757             Jupiter Ascending   85.369080   2015-02-04
46          18  26672     The Thief and the Cobbler    2.439184   1993-09-23
53          20  15301      Twilight Zone: The Movie   12.902975   1983-06-24

    movie_id            genre
9      49529  Science Fiction
17     18841  Science Fiction
21     76757  Science Fiction
46     26672  Science Fiction
53     15301  Science Fiction
(535, 7)
    Unnamed: 0      id                                             title  \
11           5   49529                                       John Carter
20          10   76757                                 Jupiter Ascending
34          14  308531  Teenage Mutant Ninja Turtles: Out of the Shadows
71          30   19995                                            Avatar
79          32   27205                                         Inception

    popularity release_date  movie_id   genre
11   43.926995   2012-03-07     49529  Action
20   85.369080   2015-02-04     76757  Action
34   39.873791   2016-06-01    308531  Action
71  150.437577   2009-12-10     19995  Action
79  167.583710   2010-07-14     27205  Action
(1154, 7)

In [49]:
df_left= action_movie.merge(sci_movie, on='movie_id', how='left', suffixes=('_action','_scifi'))
df_left.head()
#demostrar la union izquierda
#aqui se muestra que una pelicula se puede tomar para varios generos

,Unnamed: 0_action,id_action,title_action,popularity_action,release_date_action,movie_id,genre_action,Unnamed: 0_scifi,id_scifi,title_scifi,popularity_scifi,release_date_scifi,genre_scifi
0,5,49529,John Carter,43.926995,2012-03-07,49529,Action,5.0,49529.0,John Carter,43.926995,2012-03-07,Science Fiction
1,10,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Action,10.0,76757.0,Jupiter Ascending,85.369080,2015-02-04,Science Fiction
2,14,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,39.873791,2016-06-01,308531,Action,NaN,NaN,NaN,NaN,NaN,NaN
3,30,19995,Avatar,150.437577,2009-12-10,19995,Action,30.0,19995.0,Avatar,150.437577,2009-12-10,Science Fiction
4,32,27205,Inception,167.583710,2010-07-14,27205,Action,32.0,27205.0,Inception,167.583710,2010-07-14,Science Fiction

In [50]:
df_right= action_movie.merge(sci_movie, on='movie_id', how='right', suffixes=('_action','_scifi'))
df_right.head()
#demostrar la union derecha

,Unnamed: 0_action,id_action,title_action,popularity_action,release_date_action,movie_id,genre_action,Unnamed: 0_scifi,id_scifi,title_scifi,popularity_scifi,release_date_scifi,genre_scifi
0,5.0,49529.0,John Carter,43.926995,2012-03-07,49529,Action,5,49529,John Carter,43.926995,2012-03-07,Science Fiction
1,NaN,NaN,NaN,NaN,NaN,18841,NaN,9,18841,The Lost Skeleton of Cadavra,1.680525,2001-09-12,Science Fiction
2,10.0,76757.0,Jupiter Ascending,85.369080,2015-02-04,76757,Action,10,76757,Jupiter Ascending,85.369080,2015-02-04,Science Fiction
3,NaN,NaN,NaN,NaN,NaN,26672,NaN,18,26672,The Thief and the Cobbler,2.439184,1993-09-23,Science Fiction
4,NaN,NaN,NaN,NaN,NaN,15301,NaN,20,15301,Twilight Zone: The Movie,12.902975,1983-06-24,Science Fiction